### ISSUE TITLE
Serial Connection Fails

### ISSUE THREAD

**Issue by Batron02** [ADTPro/adtpro#112] opened 2020-08-06 01:03 UTC
Trying to get my IIGS up and running and after I click the Serial button the program crashes and gives me this same error file.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000180005b00, pid=6264, tid=0x00000000000025b8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [rxtxSerial.dll+0x5b00]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

I have put the proper files from ADT into the Java folder and I still get the same error message. Please help.

**Comment by david-schmidt** [comment] 2020-08-06 01:09
Duplicate of: https://github.com/ADTPro/adtpro/issues/110

**Closed by david-schmidt** 2020-08-06 01:09 UTC
